#!/usr/bin/env python3
"""Generate figures for the paper 'From Qubits to Communities'.

Run from paper directory:
    python3 figures/generate_figures.py

Produces:
    figures/fig1_pipeline.png       — three-stage architecture diagram
    figures/fig2_v3_circuit.png     — V3-extended 19-qubit circuit schematic
    figures/fig3_stratification.png — two-tier regret stratification bar chart (+ ibm_fez anomaly)
    figures/fig5_exp9.png           — Exp 9 dual-mode Gini evolution
    figures/fig6_topology.png       — social topology (greedy vs QUBO placeholder)

Note: figures/fig4_society.png is generated by generate_society_visualization.py
(Option B selected for the paper).
"""

import json
import os
import sys

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER_DIR = os.path.dirname(HERE)
REPO_ROOT = os.path.dirname(os.path.dirname(PAPER_DIR))
EXP9_DIR = os.path.join(REPO_ROOT, "experiments", "results", "exp9")

# Consistent styling
plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["font.size"] = 11
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3
plt.rcParams["figure.dpi"] = 120


# =====================================================================
# FIGURE 1: Three-stage pipeline diagram
# =====================================================================

def fig1_pipeline():
    fig, ax = plt.subplots(figsize=(14, 6))
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 6)
    ax.axis("off")

    # Stage boxes
    stages = [
        (1.0, 2.5, 3.0, 2.0, "Stage 1\nSemantic Comprehension",
         "• LLM decomposition\n• Agentic critique\n• V3 quantum scoring\n  (19q, Heron R2)", "#D4E6F1"),
        (5.5, 2.5, 3.0, 2.0, "Stage 2\nVector Filtration",
         "• Classical\n  dimensionality\n  reduction\n• Eligibility filter", "#FAD7A0"),
        (10.0, 2.5, 3.0, 2.0, "Stage 3\nQUBO Optimization",
         "• 7-constraint H\n• Exhaustive / SA\n• Society snapshot\n• Cycle engine", "#ABEBC6"),
    ]

    for x, y, w, h, title, body, color in stages:
        box = FancyBboxPatch((x, y), w, h,
                              boxstyle="round,pad=0.1",
                              facecolor=color, edgecolor="black", linewidth=1.5)
        ax.add_patch(box)
        ax.text(x + w / 2, y + h - 0.35, title,
                ha="center", va="top", fontweight="bold", fontsize=12)
        ax.text(x + w / 2, y + h - 0.95, body,
                ha="center", va="top", fontsize=9)

    # Arrows between stages
    arrow_kwargs = dict(arrowstyle="->", color="black", linewidth=2)
    for x in [4.2, 8.7]:
        ax.annotate("", xy=(x + 1.2, 3.5), xytext=(x, 3.5),
                    arrowprops=arrow_kwargs)

    # Labels above arrows
    ax.text(4.75, 3.75, "similarity\nweights $w_{ij}$",
            ha="center", fontsize=9, style="italic")
    ax.text(9.25, 3.75, "weight\nvector",
            ha="center", fontsize=9, style="italic")

    # Input on the left
    ax.annotate("", xy=(1.0, 3.5), xytext=(0.1, 3.5), arrowprops=arrow_kwargs)
    ax.text(0.5, 3.8, "Natural\nlanguage\nrequest",
            ha="center", fontsize=9, style="italic")

    # Output on the right
    ax.annotate("", xy=(13.9, 3.5), xytext=(13.0, 3.5), arrowprops=arrow_kwargs)
    ax.text(13.7, 3.8, "Coordination\nassignment",
            ha="center", fontsize=9, style="italic")

    # Classical/quantum legend
    ax.add_patch(FancyBboxPatch((5.5, 0.5), 1.2, 0.6,
                                 boxstyle="round,pad=0.05",
                                 facecolor="#A9DFBF", edgecolor="none"))
    ax.text(6.1, 0.8, "Classical", ha="center", va="center", fontsize=9)
    ax.add_patch(FancyBboxPatch((7.5, 0.5), 1.2, 0.6,
                                 boxstyle="round,pad=0.05",
                                 facecolor="#AED6F1", edgecolor="none"))
    ax.text(8.1, 0.8, "Quantum", ha="center", va="center", fontsize=9)

    ax.text(7.0, 5.5, "OrquestIA Quantum-Classical Coordination Pipeline",
            ha="center", fontsize=14, fontweight="bold")
    ax.text(7.0, 1.6, "Pipeline is classical-first: quantum enters at Stage 1 (semantic scoring), "
                      "classical solves Stage 3 (NP-hard QUBO)",
            ha="center", fontsize=9, style="italic", color="dimgray")

    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig1_pipeline.png"), bbox_inches="tight")
    plt.close(fig)
    print("  wrote fig1_pipeline.png")


# =====================================================================
# FIGURE 2: V3-extended 19-qubit circuit schematic (supplementary)
# =====================================================================

def fig2_v3_circuit():
    fig, ax = plt.subplots(figsize=(14, 8))
    ax.set_xlim(0, 14)
    ax.set_ylim(-0.5, 20)
    ax.axis("off")

    N = 19
    y_positions = list(range(N))
    labels = [f"v1[{i}]" for i in range(9)] + [f"v2[{i-9}]" for i in range(9, 18)] + ["ancilla"]

    # Draw qubit lines
    for i, y in enumerate(y_positions):
        ax.plot([0.5, 13.5], [y, y], "k-", lw=0.8, alpha=0.4)
        ax.text(0.1, y, labels[i], ha="right", va="center", fontsize=8)

    # Layer 1: RY encoding (columns 1.0 - 1.8)
    for y in range(9):
        ax.add_patch(Rectangle((1.0, y - 0.25), 0.7, 0.5, facecolor="#D4E6F1", edgecolor="black"))
        ax.text(1.35, y, "RY", ha="center", va="center", fontsize=7)
    for y in range(9, 18):
        ax.add_patch(Rectangle((1.0, y - 0.25), 0.7, 0.5, facecolor="#FAD7A0", edgecolor="black"))
        ax.text(1.35, y, "RY", ha="center", va="center", fontsize=7)

    # Layer 1: trainable RY (2.5 - 3.2)
    for y in range(N):
        ax.add_patch(Rectangle((2.5, y - 0.25), 0.7, 0.5, facecolor="#ABEBC6", edgecolor="black"))
        ax.text(2.85, y, "θ₁", ha="center", va="center", fontsize=7)

    # CX to ancilla (Layer 1 entanglement, cols 4.0-4.5)
    for y in range(18):
        ax.plot([4.2, 4.2], [y, 18], "k-", lw=0.5)
        ax.plot(4.2, y, "ko", markersize=3)
    ax.plot(4.2, 18, "s", color="white", markeredgecolor="black", markersize=10)
    ax.text(4.2, 18.5, "⊕", ha="center", va="bottom", fontsize=10)

    # Layer 2: trainable RY (5.5-6.2)
    for y in range(N):
        ax.add_patch(Rectangle((5.5, y - 0.25), 0.7, 0.5, facecolor="#ABEBC6", edgecolor="black"))
        ax.text(5.85, y, "θ₂", ha="center", va="center", fontsize=7)

    # Cross-register CX (v1[i] ↔ v2[i])
    for i in range(9):
        ax.plot([7.2, 7.2], [i, i + 9], "r-", lw=0.8, alpha=0.7)
        ax.plot(7.2, i, "ro", markersize=3)
        ax.plot(7.2, i + 9, "s", color="white", markeredgecolor="red", markersize=6)

    # Layer 3: trainable RY (8.5-9.2)
    for y in range(N):
        ax.add_patch(Rectangle((8.5, y - 0.25), 0.7, 0.5, facecolor="#ABEBC6", edgecolor="black"))
        ax.text(8.85, y, "θ₃", ha="center", va="center", fontsize=7)

    # Final CX to ancilla from q0 and q9
    ax.plot([10.3, 10.3], [0, 18], "b-", lw=0.5)
    ax.plot(10.3, 0, "bo", markersize=4)
    ax.plot(10.3, 18, "s", color="white", markeredgecolor="blue", markersize=10)

    ax.plot([10.8, 10.8], [9, 18], "b-", lw=0.5)
    ax.plot(10.8, 9, "bo", markersize=4)
    ax.plot(10.8, 18, "s", color="white", markeredgecolor="blue", markersize=10)

    # Measurement
    ax.add_patch(Rectangle((12.5, 17.7), 0.7, 0.6, facecolor="#E5E8E8", edgecolor="black"))
    ax.text(12.85, 18, "M", ha="center", va="center", fontsize=9, fontweight="bold")

    # Layer annotations on top
    for x, label in [(1.35, "Encoding"), (2.85, "Layer 1"),
                     (4.2, "Entangle\nto ancilla"), (5.85, "Layer 2"),
                     (7.2, "Cross\nregister"), (8.85, "Layer 3"),
                     (10.5, "Final\nCX"), (12.85, "Measure")]:
        ax.text(x, 19.3, label, ha="center", va="bottom", fontsize=8, style="italic")

    # Side labels
    ax.text(-0.3, 4, "Member\nvector\n(9 qubits)", ha="right", va="center",
            fontsize=9, color="#2874A6", fontweight="bold")
    ax.text(-0.3, 13, "Task\nvector\n(9 qubits)", ha="right", va="center",
            fontsize=9, color="#D68910", fontweight="bold")
    ax.text(-0.3, 18, "Readout", ha="right", va="center",
            fontsize=9, color="black", fontweight="bold")

    ax.text(7, -0.5, "V3-extended: 19 qubits, 57 trainable parameters. Physical depth "
                    "167–270 on IBM Heron R2 after SWAP routing.",
            ha="center", fontsize=10, style="italic", color="dimgray")

    fig.suptitle("V3-Extended Quantum Circuit for Semantic Similarity",
                 fontsize=14, fontweight="bold", y=0.98)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig2_v3_circuit.png"), bbox_inches="tight")
    plt.close(fig)
    print("  wrote fig2_v3_circuit.png")


# =====================================================================
# FIGURE 3: Two-tier regret stratification (+ unreproduced anomaly)
# =====================================================================

def fig3_stratification():
    fig, ax = plt.subplots(figsize=(11, 6))

    # Three-tier stratification with kingston validation:
    #   Noiseless ceiling (1.48%): all five logical-depth controls + ibm_marrakesh
    #   Classical-kernel tier (0.86%): K_c dequantization
    #   Hardware tier (0.61%): ibm_fez + ibm_kingston (n=2 chip replication)
    methods = [
        ("Arm A\nnoiseless", 1.48, 0.00, "#95A5A6"),
        ("Arm B\nlogical depth\n(30 traj.)", 1.48, 0.00, "#95A5A6"),
        ("Arm B'\nrouting depth\n(5 traj.)", 1.48, 0.00, "#95A5A6"),
        ("Arm C\n57-param MLP", 1.48, 0.00, "#95A5A6"),
        ("ibm_marrakesh\n(hardware)", 1.48, 0.00, "#85C1E9"),
        ("Arm D\n$K_c$ kernel", 0.86, 0.00, "#F7DC6F"),
        ("ibm_fez\n(hardware)", 0.61, 0.00, "#58D68D"),
        ("ibm_kingston\n(hardware, NEW)", 0.61, 0.00, "#58D68D"),
    ]

    names = [m[0] for m in methods]
    regrets = [m[1] for m in methods]
    errors = [m[2] for m in methods]
    colors = [m[3] for m in methods]

    x = np.arange(len(names))
    bars = ax.bar(x, regrets, yerr=errors, capsize=5, color=colors,
                   edgecolor="black", linewidth=1.2)

    # Three horizontal tier lines: noiseless ceiling, K_c, hardware tier.
    ax.axhline(1.48, color="#7F8C8D", linestyle="--", linewidth=1, alpha=0.7)
    ax.axhline(0.86, color="#B7950B", linestyle="--", linewidth=1.2, alpha=0.9)
    ax.axhline(0.61, color="#229954", linestyle="--", linewidth=1.2, alpha=0.9)

    # Tier labels with semi-transparent white box for readability over bars
    label_bbox = dict(boxstyle="round,pad=0.25", facecolor="white",
                      edgecolor="none", alpha=0.85)
    ax.text(0.05, 1.34,
            "Noiseless ceiling (1.48%) — 5 simulator controls + ibm_marrakesh (logical-depth RKHS)",
            ha="left", va="top", fontsize=9, style="italic", color="#566573",
            bbox=label_bbox)
    ax.text(0.05, 0.73,
            "Classical-kernel tier (0.86%) — $K_c$ is the deployable upgrade (provable RKHS ceiling)",
            ha="left", va="top", fontsize=9, style="italic", color="#B7950B",
            bbox=label_bbox)
    ax.text(0.05, 0.50,
            "Hardware tier (0.61%) — ibm_fez + ibm_kingston, n=2 chip replication (outside RKHS)",
            ha="left", va="top", fontsize=9, style="italic", color="#229954",
            bbox=label_bbox)

    # Annotation noting n=2 chip replication on hardware tier.
    ax.annotate(
        "n=2 chip replication (same θ):\n"
        "ibm_fez (2026-04-10) + ibm_kingston (2026-04-16)\n"
        "both reach 0.61% with identical seed-42 θ.\n"
        "ibm_marrakesh is the outlier chip at 1.48%.",
        xy=(6.5, 0.62), xytext=(2.2, 0.22),
        fontsize=8, color="#1E8449",
        bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                  edgecolor="#229954", alpha=0.9),
        arrowprops=dict(arrowstyle="->", color="#229954", lw=0.8),
    )

    # Bar value labels
    for i, (r, e) in enumerate(zip(regrets, errors)):
        label = f"{r:.2f}%"
        if e == 0.0 and i < 4:
            label += "\n$\\pm$ 0.00"
        ax.text(i, r + 0.05, label, ha="center", fontsize=9, fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(names, fontsize=9)
    ax.set_ylabel("Mean Classical Regret (%)", fontsize=11)
    ax.set_ylim(0, 1.85)
    ax.set_title("Three-Tier Regret Stratification — Mechanism Isolation + Multi-Chip Hardware",
                 fontsize=13, fontweight="bold")

    # Legend for colors
    from matplotlib.patches import Patch
    legend_items = [
        Patch(facecolor="#95A5A6", edgecolor="black", label="Simulator / classical (logical-depth RKHS)"),
        Patch(facecolor="#85C1E9", edgecolor="black", label="ibm_marrakesh (hardware, 1.48% mode)"),
        Patch(facecolor="#F7DC6F", edgecolor="black", label="$K_c$ dequantization kernel (provable RKHS ceiling)"),
        Patch(facecolor="#58D68D", edgecolor="black", label="ibm_fez + ibm_kingston (hardware, outside RKHS)"),
    ]
    ax.legend(handles=legend_items, loc="upper right", fontsize=8)

    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig3_stratification.png"), bbox_inches="tight")
    plt.close(fig)
    print("  wrote fig3_stratification.png")


# =====================================================================
# FIGURE 4: Exp 9 dual-mode Gini evolution
# =====================================================================

def _load_gini_series(path):
    """Extract per-architecture Gini series from exp9 JSON."""
    with open(path) as f:
        data = json.load(f)
    series = {}
    for arch in ["linear", "skill_only", "acceptance", "kc_9d", "kc_12d"]:
        if arch not in data:
            continue
        entries = data[arch].get("gini_series", [])
        cycles = [e[0] for e in entries]
        ginis = [e[1] for e in entries]
        series[arch] = (cycles, ginis)
    return series, data


def fig5_exp9():
    """Two-panel figure: 1x/day and 3x/day Gini evolution across architectures."""
    path_1x = os.path.join(EXP9_DIR, "exp9_m.json")
    path_3x = os.path.join(EXP9_DIR, "exp9_m_3x.json")

    if not (os.path.exists(path_1x) and os.path.exists(path_3x)):
        print(f"  SKIP fig4 — missing {path_1x} or {path_3x}")
        return

    series_1x, data_1x = _load_gini_series(path_1x)
    series_3x, data_3x = _load_gini_series(path_3x)

    fig, (ax_top, ax_bot) = plt.subplots(2, 1, figsize=(11, 9), sharex=False)

    colors = {
        "linear":      "#E74C3C",
        "skill_only":  "#F39C12",
        "acceptance":  "#27AE60",
        "kc_9d":       "#2874A6",
        "kc_12d":      "#8E44AD",
    }
    labels = {
        "linear":     "Linear (paper formula)",
        "skill_only": "Skill-only",
        "acceptance": "Acceptance (sigmoid)",
        "kc_9d":      "$K_c$ 9D (dequantization)",
        "kc_12d":     "$K_c$ 12D (full vector)",
    }

    for arch, (cycles, ginis) in series_1x.items():
        ax_top.plot(cycles, ginis, marker="o", color=colors[arch],
                    label=labels[arch], linewidth=2, markersize=5)

    for arch, (cycles, ginis) in series_3x.items():
        ax_bot.plot(cycles, ginis, marker="o", color=colors[arch],
                    label=labels[arch], linewidth=2, markersize=4)

    for ax, title, xlabel in [
        (ax_top, "Mode A: 1×/day (energy resets each cycle)", "Cycle"),
        (ax_bot, "Mode B: 3×/day (energy depletes across rounds, age-based overnight recovery)", "Cycle"),
    ]:
        ax.set_title(title, fontsize=12, fontweight="bold")
        ax.set_xlabel(xlabel, fontsize=10)
        ax.set_ylabel("Gini coefficient", fontsize=10)
        ax.legend(loc="lower right", fontsize=9, ncol=2)
        ax.set_ylim(0.25, 0.55)
        ax.grid(alpha=0.3)

    # Annotation callouts
    ax_top.annotate("$K_c$ 9D wins equity\n(0.375)",
                    xy=(30, 0.375), xytext=(24, 0.29),
                    fontsize=9, color="#2874A6", fontweight="bold",
                    arrowprops=dict(arrowstyle="->", color="#2874A6", lw=1.2))
    ax_bot.annotate("All architectures\nconverge (range 0.01)",
                    xy=(90, 0.42), xytext=(70, 0.52),
                    fontsize=9, color="black", fontweight="bold",
                    arrowprops=dict(arrowstyle="->", color="black", lw=1.2))

    fig.suptitle("Exp 9: Pipeline Architecture Comparison on Society Model\n"
                 "Structural realism (households + tools + age) compresses architecture differences;\n"
                 "temporal frequency becomes the dominant policy lever",
                 fontsize=13, fontweight="bold", y=1.0)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig5_exp9.png"), bbox_inches="tight")
    plt.close(fig)
    print("  wrote fig5_exp9.png")


# =====================================================================
# FIGURE 5: Social topology — greedy vs QUBO (schematic)
# =====================================================================

def fig6_topology():
    """Schematic of Louvain clusters + inter-cluster bridges for two strategies."""
    fig, (ax_g, ax_q) = plt.subplots(1, 2, figsize=(14, 7))

    rng = np.random.default_rng(42)

    # Create 4 clusters of ~12 nodes each (48 total, simplification of 500)
    clusters = []
    centers = [(2, 2), (6, 2), (2, 6), (6, 6)]
    cluster_colors = ["#E74C3C", "#F39C12", "#27AE60", "#2874A6"]

    for cx, cy in centers:
        pts = rng.normal(loc=[cx, cy], scale=0.6, size=(12, 2))
        clusters.append(pts)

    def draw_graph(ax, intra_edges_per_cluster, inter_edges, title, bridge_count_text):
        # Draw cluster nodes
        for cid, pts in enumerate(clusters):
            ax.scatter(pts[:, 0], pts[:, 1], s=80,
                       c=cluster_colors[cid], edgecolors="black",
                       linewidth=0.8, zorder=3)
        # Intra-cluster edges
        for cid, pts in enumerate(clusters):
            n = len(pts)
            for _ in range(intra_edges_per_cluster):
                i, j = rng.integers(0, n, size=2)
                if i != j:
                    ax.plot([pts[i, 0], pts[j, 0]], [pts[i, 1], pts[j, 1]],
                            color=cluster_colors[cid], alpha=0.3, lw=1, zorder=1)
        # Inter-cluster edges (bridges)
        for _ in range(inter_edges):
            c1, c2 = rng.choice(4, size=2, replace=False)
            i = rng.integers(0, len(clusters[c1]))
            j = rng.integers(0, len(clusters[c2]))
            ax.plot([clusters[c1][i, 0], clusters[c2][j, 0]],
                    [clusters[c1][i, 1], clusters[c2][j, 1]],
                    "k-", alpha=0.55, lw=1.3, zorder=2)

        ax.set_xlim(0, 8)
        ax.set_ylim(0, 8)
        ax.set_aspect("equal")
        ax.set_title(title, fontsize=12, fontweight="bold")
        ax.text(4, 0.3, bridge_count_text, ha="center", fontsize=11, fontweight="bold",
                color="#1A5276")
        ax.set_xticks([])
        ax.set_yticks([])

    draw_graph(ax_g, intra_edges_per_cluster=20, inter_edges=10,
               title="Greedy Matching",
               bridge_count_text="Bridges ≈ 8,115 | Clustering 0.184 | PI 1.0×")
    draw_graph(ax_q, intra_edges_per_cluster=25, inter_edges=22,
               title="QUBO Matching (Granovetter machine)",
               bridge_count_text="Bridges ≈ 14,735 | Clustering 0.222 | PI 2.10×")

    fig.suptitle("Emergent Social Topology: Greedy vs. QUBO (schematic; 7-run means)",
                 fontsize=13, fontweight="bold")
    ax_q.text(4, -0.3, "+81% bridges, $A_{12} = 1.0$, $p < 0.001$",
              ha="center", fontsize=10, color="#229954", fontweight="bold")

    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "fig6_topology.png"), bbox_inches="tight")
    plt.close(fig)
    print("  wrote fig6_topology.png")


# =====================================================================
# Main
# =====================================================================

if __name__ == "__main__":
    print("Generating paper figures...")
    fig1_pipeline()
    fig2_v3_circuit()
    fig3_stratification()
    fig5_exp9()
    fig6_topology()
    print("Done. Figures saved in", HERE)
